<a href="https://colab.research.google.com/github/ram1014/colab_files/blob/main/Practica4_263165.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Practica 4

Manipulación de matrices.

Crea dos matrices de 3x3 con números aleatorios entre 1 y 10. Realiza las siguientes operaciones:

  1.   Suma ambas matrices.
  2.   Resta la segunda matriz de la primera.
  3.   Multiplica la primera matriz por 2.
  4.   Realiza una multiplicación matricial entre las dos matrices.




In [1]:
import numpy as np

matrix1 = np.random.randint(1, 10, (3,3))
matrix2 = np.random.randint(1, 10, (3,3))
print(f"Random Matrices are \nMatrix1:\n{matrix1}\n\nMatrix2:\n{matrix2}\n")

#Suma ambas matrices.
matrix3 = matrix1 + matrix2
print(f"Matrix1 + Matrix2 = \n {matrix3}")

#Resta la segunda matriz de la primera.
matrix4 = matrix1 - matrix2
print(f"Matrix1 - Matrix2 = \n {matrix4}")

#Multiplica la primera matriz por 2.
matrix5 = matrix1 * 2
print(f"Matrix1 * 2 = \n {matrix5}")

#Realiza una multiplicación matricial entre las dos matrices.
matrix6 = matrix1 @ matrix2
print(f"Matrix1 X Matrix2 = \n {matrix6}")


Random Matrices are 
Matrix1:
[[2 1 3]
 [7 3 2]
 [3 8 8]]

Matrix2:
[[5 3 2]
 [2 6 2]
 [3 4 5]]

Matrix1 + Matrix2 = 
 [[ 7  4  5]
 [ 9  9  4]
 [ 6 12 13]]
Matrix1 - Matrix2 = 
 [[-3 -2  1]
 [ 5 -3  0]
 [ 0  4  3]]
Matrix1 * 2 = 
 [[ 4  2  6]
 [14  6  4]
 [ 6 16 16]]
Matrix1 X Matrix2 = 
 [[21 24 21]
 [47 47 30]
 [55 89 62]]
